export const initialFilterState = {
  selectedFilter: "none",
};

export const filterCategories = {
  "None": ["None"],
  "Natural": ["Fresce", "Belvedere", "Flint", "Luna", "Aero", "Myst"],
  "Warm": ["Bali", "Capri", "Latte", "Bronz", "Sandi", "Sangri"],
  "Cool": ["Scandi", "Nordic", "Astro", "Arctic", "Polar", "Tundra"],
  "Vivid": ["Chroma", "Rustiq", "Eldar", "Zeal", "Aria", "Stark"],
  "Soft": ["Aura", "Hazel", "Whimsi", "Rose", "Oceanic", "Nimbus"],
  "Vintage": ["Vinto", "Fade", "Antiq", "Nostalg", "Dream", "Retro"],
  "Mono": ["Classic", "Ink", "Noir", "Film", "Newspaper", "Slate"],
  // "Color Pop": ["Octrun", "Heatwave", "Amethyst", "Minty", "Poster", "X-Pro-", "X-Pro+"],
};

export const filterAdjustments = {
  "None": { adjustments: { brightness: 0, contrast: 0, saturation: 0, vibrance: 0, temperature: 0, tint: 0, sharpness: 0, clarity: 0, vignette: 0, invert: false }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Fresce": { adjustments: { sepia: 0.3, saturation: 20, brightness: 10, vignette: 10 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Belvedere": { adjustments: { contrast: 20, brightness: -10, saturation: 10, vignette: 15 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Flint": { adjustments: { grayscale: 0.2, contrast: 10, brightness: -5, vignette: 20 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Luna": { adjustments: { brightness: 10, contrast: -10, saturation: -20, vignette: 10 }, colorAdjustments: { hue: 10, saturation: 0, brightness: 0 } },
  "Aero": { adjustments: { brightness: 5, contrast: 10, saturation: 10, vignette: 15 }, colorAdjustments: { hue: -5, saturation: 0, brightness: 0 } },
  "Myst": { adjustments: { brightness: -5, contrast: 5, saturation: -10, clarity: 5, vignette: 20 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Bali": { adjustments: { sepia: 0.4, saturation: 30, brightness: 10, vignette: 25 }, colorAdjustments: { hue: 15, saturation: 0, brightness: 0 } },
  "Capri": { adjustments: { sepia: 0.2, saturation: 20, brightness: 5, vignette: 20 }, colorAdjustments: { hue: 20, saturation: 0, brightness: 0 } },
  "Latte": { adjustments: { sepia: 0.5, saturation: 10, brightness: 10, vignette: 15 }, colorAdjustments: { hue: 25, saturation: 0, brightness: 0 } },
  "Bronz": { adjustments: { sepia: 0.3, saturation: 40, brightness: -5, vignette: 20 }, colorAdjustments: { hue: 30, saturation: 0, brightness: 0 } },
  "Sandi": { adjustments: { sepia: 0.6, saturation: 20, brightness: 5, vignette: 25 }, colorAdjustments: { hue: 35, saturation: 0, brightness: 0 } },
  "Sangri": { adjustments: { sepia: 0.4, saturation: 50, brightness: 0, vignette: 30 }, colorAdjustments: { hue: 40, saturation: 0, brightness: 0 } },
  "Scandi": { adjustments: { brightness: 10, contrast: -10, saturation: -20, vignette: 15 }, colorAdjustments: { hue: -15, saturation: 0, brightness: 0 } },
  "Nordic": { adjustments: { brightness: 5, contrast: 10, saturation: -30, vignette: 20 }, colorAdjustments: { hue: -20, saturation: 0, brightness: 0 } },
  "Astro": { adjustments: { brightness: -5, contrast: 20, saturation: -10, vignette: 25 }, colorAdjustments: { hue: -25, saturation: 0, brightness: 0 } },
  "Arctic": { adjustments: { brightness: 10, contrast: -20, saturation: -40, vignette: 20 }, colorAdjustments: { hue: -30, saturation: 0, brightness: 0 } },
  "Polar": { adjustments: { brightness: 20, contrast: -10, saturation: -50, vignette: 15 }, colorAdjustments: { hue: -35, saturation: 0, brightness: 0 } },
  "Tundra": { adjustments: { brightness: 0, contrast: 10, saturation: -30, vignette: 20 }, colorAdjustments: { hue: -40, saturation: 0, brightness: 0 } },
  "Chroma": { adjustments: { saturation: 100, contrast: 30, brightness: 0, vignette: 25 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Rustiq": { adjustments: { saturation: 80, contrast: 20, brightness: -5, vignette: 20 }, colorAdjustments: { hue: 10, saturation: 0, brightness: 0 } },
  "Eldar": { adjustments: { saturation: 90, contrast: 40, brightness: 5, vignette: 15 }, colorAdjustments: { hue: -10, saturation: 0, brightness: 0 } },
  "Zeal": { adjustments: { saturation: 120, contrast: 30, brightness: 10, vignette: 20 }, colorAdjustments: { hue: 5, saturation: 0, brightness: 0 } },
  "Aria": { adjustments: { saturation: 70, contrast: 10, brightness: 15, vignette: 25 }, colorAdjustments: { hue: -5, saturation: 0, brightness: 0 } },
  "Stark": { adjustments: { saturation: 60, contrast: 50, brightness: -10, vignette: 20 }, colorAdjustments: { hue: 15, saturation: 0, brightness: 0 } },
  "Aura": { adjustments: { brightness: 20, contrast: -20, saturation: -10, clarity: 10, vignette: 15 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Hazel": { adjustments: { brightness: 10, contrast: -10, saturation: 10, sepia: 0.1, vignette: 20 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Whimsi": { adjustments: { brightness: 15, contrast: -15, saturation: 20, vignette: 15 }, colorAdjustments: { hue: 5, saturation: 0, brightness: 0 } },
  "Rose": { adjustments: { brightness: 10, contrast: -10, saturation: 30, vignette: 20 }, colorAdjustments: { hue: -10, saturation: 0, brightness: 0 } },
  "Oceanic": { adjustments: { brightness: 5, contrast: -5, saturation: 10, vignette: 15 }, colorAdjustments: { hue: -15, saturation: 0, brightness: 0 } },
  "Nimbus": { adjustments: { brightness: 20, contrast: -30, saturation: -20, clarity: 5, vignette: 20 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Vinto": { adjustments: { sepia: 0.8, contrast: 20, brightness: -10, saturation: 10, vignette: 25 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Fade": { adjustments: { sepia: 0.6, contrast: -20, brightness: 10, saturation: -10, vignette: 20 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Antiq": { adjustments: { sepia: 1.0, contrast: 10, brightness: -15, saturation: 20, vignette: 25 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Nostalg": { adjustments: { sepia: 0.7, contrast: 30, brightness: -5, saturation: 0, vignette: 20 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Dream": { adjustments: { sepia: 0.5, contrast: -10, brightness: 20, saturation: -20, clarity: 5, vignette: 15 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Retro": { adjustments: { sepia: 0.9, contrast: 40, brightness: -20, saturation: 30, vignette: 25 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Classic": { adjustments: { grayscale: 1.0, contrast: 20, brightness: -5, vignette: 20 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Ink": { adjustments: { grayscale: 1.0, contrast: 50, brightness: -20, vignette: 25 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Noir": { adjustments: { grayscale: 1.0, contrast: 80, brightness: -30, vignette: 30 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Film": { adjustments: { grayscale: 1.0, contrast: 10, brightness: 0, sepia: 0.1, vignette: 20 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Newspaper": { adjustments: { grayscale: 1.0, contrast: 100, brightness: 20, vignette: 15 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "Slate": { adjustments: { grayscale: 1.0, contrast: 30, brightness: -10, vignette: 20 }, colorAdjustments: { hue: 180, saturation: 0, brightness: 0 } },
  "Octrun": { adjustments: { saturation: -100, contrast: 50, brightness: 10, vignette: 25 }, colorAdjustments: { hue: 45, saturation: 0, brightness: 0 } },
  "Heatwave": { adjustments: { saturation: -100, contrast: 30, brightness: 0, vignette: 20 }, colorAdjustments: { hue: 15, saturation: 0, brightness: 0 } },
  "Amethyst": { adjustments: { saturation: -100, contrast: 20, brightness: 5, vignette: 15 }, colorAdjustments: { hue: 270, saturation: 0, brightness: 0 } },
  "Minty": { adjustments: { saturation: -100, contrast: 10, brightness: 10, vignette: 20 }, colorAdjustments: { hue: 120, saturation: 0, brightness: 0 } },
  "Poster": { adjustments: { saturation: -100, contrast: 100, brightness: -10, vignette: 25 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "X-Pro-": { adjustments: { saturation: -100, contrast: 40, brightness: -15, sepia: 0.2, vignette: 30 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
  "X-Pro+": { adjustments: { saturation: -100, contrast: 60, brightness: 15, sepia: 0.1, vignette: 25 }, colorAdjustments: { hue: 0, saturation: 0, brightness: 0 } },
};

export const getFilterCSS = (filter) => {
  const filterMap = {
    "None": "none",
    "Fresce": "sepia(0.3) saturate(1.2) brightness(1.1)",
    "Belvedere": "contrast(1.2) brightness(0.9) saturate(1.1)",
    "Flint": "grayscale(0.2) contrast(1.1) brightness(0.95)",
    "Luna": "brightness(1.1) contrast(0.9) saturate(0.8) hue-rotate(10deg)",
    "Aero": "brightness(1.05) contrast(1.1) saturate(1.1) hue-rotate(-5deg)",
    "Myst": "brightness(0.95) contrast(1.05) saturate(0.9) blur(0.5px)",
    "Bali": "sepia(0.4) saturate(1.3) brightness(1.1) hue-rotate(15deg)",
    "Capri": "sepia(0.2) saturate(1.2) brightness(1.05) hue-rotate(20deg)",
    "Latte": "sepia(0.5) saturate(1.1) brightness(1.1) hue-rotate(25deg)",
    "Bronz": "sepia(0.3) saturate(1.4) brightness(0.95) hue-rotate(30deg)",
    "Sandi": "sepia(0.6) saturate(1.2) brightness(1.05) hue-rotate(35deg)",
    "Sangri": "sepia(0.4) saturate(1.5) brightness(1.0) hue-rotate(40deg)",
    "Scandi": "brightness(1.1) contrast(0.9) saturate(0.8) hue-rotate(-15deg)",
    "Nordic": "brightness(1.05) contrast(1.1) saturate(0.7) hue-rotate(-20deg)",
    "Astro": "brightness(0.95) contrast(1.2) saturate(0.9) hue-rotate(-25deg)",
    "Arctic": "brightness(1.1) contrast(0.8) saturate(0.6) hue-rotate(-30deg)",
    "Polar": "brightness(1.2) contrast(0.9) saturate(0.5) hue-rotate(-35deg)",
    "Tundra": "brightness(1.0) contrast(1.1) saturate(0.7) hue-rotate(-40deg)",
    "Chroma": "saturate(2.0) contrast(1.3) brightness(1.0)",
    "Rustiq": "saturate(1.8) contrast(1.2) brightness(0.95) hue-rotate(10deg)",
    "Eldar": "saturate(1.9) contrast(1.4) brightness(1.05) hue-rotate(-10deg)",
    "Zeal": "saturate(2.2) contrast(1.3) brightness(1.1) hue-rotate(5deg)",
    "Aria": "saturate(1.7) contrast(1.1) brightness(1.15) hue-rotate(-5deg)",
    "Stark": "saturate(1.6) contrast(1.5) brightness(0.9) hue-rotate(15deg)",
    "Aura": "brightness(1.2) contrast(0.8) saturate(0.9) blur(1px)",
    "Hazel": "brightness(1.1) contrast(0.9) saturate(1.1) sepia(0.1)",
    "Whimsi": "brightness(1.15) contrast(0.85) saturate(1.2) hue-rotate(5deg)",
    "Rose": "brightness(1.1) contrast(0.9) saturate(1.3) hue-rotate(-10deg)",
    "Oceanic": "brightness(1.05) contrast(0.95) saturate(1.1) hue-rotate(-15deg)",
    "Nimbus": "brightness(1.2) contrast(0.7) saturate(0.8) blur(0.5px)",
    "Vinto": "sepia(0.8) contrast(1.2) brightness(0.9) saturate(1.1)",
    "Fade": "sepia(0.6) contrast(0.8) brightness(1.1) saturate(0.9)",
    "Antiq": "sepia(1.0) contrast(1.1) brightness(0.85) saturate(1.2)",
    "Nostalg": "sepia(0.7) contrast(1.3) brightness(0.95) saturate(1.0)",
    "Dream": "sepia(0.5) contrast(0.9) brightness(1.2) saturate(0.8) blur(0.5px)",
    "Retro": "sepia(0.9) contrast(1.4) brightness(0.8) saturate(1.3)",
    "Classic": "grayscale(1.0) contrast(1.2) brightness(0.95)",
    "Ink": "grayscale(1.0) contrast(1.5) brightness(0.8)",
    "Noir": "grayscale(1.0) contrast(1.8) brightness(0.7)",
    "Film": "grayscale(1.0) contrast(1.1) brightness(1.0) sepia(0.1)",
    "Newspaper": "grayscale(1.0) contrast(2.0) brightness(1.2)",
    "Slate": "grayscale(1.0) contrast(1.3) brightness(0.9) hue-rotate(180deg)",
    "Octrun": "saturate(0) contrast(1.5) brightness(1.1) hue-rotate(45deg)",
    "Heatwave": "saturate(0) contrast(1.3) brightness(1.0) hue-rotate(15deg)",
    "Amethyst": "saturate(0) contrast(1.2) brightness(1.05) hue-rotate(270deg)",
    "Minty": "saturate(0) contrast(1.1) brightness(1.1) hue-rotate(120deg)",
    "Poster": "saturate(0) contrast(2.0) brightness(0.9)",
    "X-Pro-": "saturate(0) contrast(1.4) brightness(0.85) sepia(0.2)",
    "X-Pro+": "saturate(0) contrast(1.6) brightness(1.15) sepia(0.1)",
  };

  return filterMap[filter] || "none";
};